apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: u5qx28kzd-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/u5qx28kzd-java-springboot-gitops